### ISSUE TITLE
Be able to edit other file formats than md (eg. txt)

### ISSUE THREAD

**Issue by hakanu** [hakanu/pervane#1]
Make it configurable via a flag with the list type.

**Comment by Tugberk** [comment]
Just editing md files. It would be great if we could select which file extensions can be edited automatically.

**Comment by hakanu** [comment]
abcd12be1039d955f5c4ab0784e8aab2b97f22dc added this feature.

Default extensions: .md, .markdown, .txt; can be modified while running the app

pervane --dir=/tmp/foo --note_extensions=".text"
