### ISSUE TITLE
How do I install `pervane` on Windows 7? (pervane)

### ISSUE THREAD

**Issue by it19862** [hakanu/pervane#148]
How do I install `pervane` on Windows 7? (pervane)

**Comment by hakanu** [comment]
1. win + R
2. Type `cmd.exe`, hit enter
3. Run this `pip install pervane` should do it.

Alternatively:
Here are more options: https://github.com/hakanu/pervane/wiki/Install-&-Run-instructions#install

**Comment by hakanu** [comment]
Closing assuming that your issue is fixed.
