### ISSUE TITLE
Font family config setting

### ISSUE THREAD

**Issue by anthbrtn** [hakanu/pervane#151]
Hey there! Wanted to say thanks for the project -- it's really surprising how much of a niche it fills and I'm grateful for your work. I've been attempting to hack this onto a fork so I could merge it, but figured I'd throw the request here because I'm not a JS developer in the slightest. I'm not a huge fan of the monospace on the file tree, nor the defualt editor.md font... any possible way to program in changing these defaults?

**Comment by hakanu** [comment]
Why did you close? it's a nice request, i will try address this as earliest :)

PS: I'm just short on time. if you feel like contributing, feel free.

**Comment by anthbrtn** [comment]
Ah whoops -- accidentally closed it when I was trying to edit my comment. And great! I'll see what I can do in the meantime :)

**Comment by hakanu** [comment]
It's tricky to change font with vue.js. Guess we can have classes with predefined fonts in the styles.css and we can use `v-if` to switch to the correct one in the dom based on the settings in the localStorage. 

Alternatively we can pass a flag named like `frontend_font_family` to the server and server propagates that to the frontend. This is not as elegant as the previous one.

May be more complicated than I initially thought. I will try some stuff today and tomorrow, let's see.

What would be a better font for you to see in the sidebar?

**Comment by anthbrtn** [comment]
I was just thinking even the sans-serif browser defaults would be nice; just thinking in terms of UI and visual flow, while monospace fonts are great for the code, having sans serif works alongside the colour differences in the sidebar from the editor to mark out the different areas

**Comment by hakanu** [comment]
I can do that real quick. Configuration may take some time.

I preferred monospace just because I want same length files to be aligned well. Guess it's not so important to keep.

**Comment by anthbrtn** [comment]
Ah yeah, I get that -- maybe different file colors for different types of files would serve the same purpose? (or confuse flow, not sure what you think). That's a change I could do no problem if you'd like.

**Comment by hakanu** [comment]
Let's try PT sans which is my favorite. (4235ae115c16faf4588c6c911b18d46e46e8e313)

You can upgrade to 0.0.80 with `pip install --upgrade pervane`

**Comment by anthbrtn** [comment]
Ah, looks great in my opinion! Thanks a ton.
