### ISSUE TITLE
file errors not capture in server log

### ISSUE THREAD

**Issue by clach04** [hakanu/pervane#154]
Errors relating to file IO not captured in the (web) server log.

This is due to using `str()` representation of exception:

    logging.error('There is an error while writing: %s. Error: %s', path, str(e))  # this does not give enough information on server

Instead either need to use `repr()`:

    logging.error('There is an error while writing: %s. Error: %r', path, e)

Or logging traceback option:

    logging.error('There is an error while writing: %s.', path, exc_info=True)

Also see #152

**Comment by hakanu** [comment]
Good catch, can you send a PR for this?

**Comment by clach04** [comment]
Let me extract the fixes from https://github.com/clach04/pervane/tree/tombo_encryption, I favor the `exc_info` approach and send in a PR.
