### ISSUE TITLE
Package Data not Installing

### ISSUE THREAD

**Issue by eslerm** [hakanu/pervane#49]
Using `setup.py` and `pip` the package data (template files, etc) do not install under Arch using Python 3.8. However, the Python egg does install.

```
$ ls /usr/lib/python3.8/site-packages/pervane*
/usr/lib/python3.8/site-packages/pervane-0.0.33-py3.8.egg
```

**Comment by hakanu** [comment]
Interesting, taking a look...

**Comment by hakanu** [comment]
Thanks for reporting the issue.

Modified MANIFEST slightly to be more inclusive. Not sure if that will fix this issue.
I can see the template files are added into the dist: https://pypi.org/project/pervane/#files

Could you please retry and let me know?

**Comment by eslerm** [comment]
Install now works. Thank you!
