### ISSUE TITLE
Pervane can read files outside of its hirearchy

### ISSUE THREAD

**Issue by carterworks** [hakanu/pervane#50]
![Example of vulnerability](https://user-images.githubusercontent.com/18412686/73274438-cb53de00-41a2-11ea-93d0-527d37e59ee5.png)

If a user starts pervane with `--dir` as a relative directory, then a potential bad actor can use other relative path commands to view system files. Attached is an example when I started Pervane with `--dir=.` and then navigated the url to `?f=./../../../../../etc/hosts` (the number of `..` doesn't matter).

My suggestion is to always resolve the absolute path when doing path logic. Don't trust the user.

**Comment by hakanu** [comment]
Great thanks! I was researching ways to penetrate that since modifying actual files through browser is error prone. Thanks for catching this. Working on it.

**Comment by hakanu** [comment]
This is fixed and released thanks for reporting!

`pip install --upgrade pervane` should do it :)
