### ISSUE TITLE
Bullet points don't render in preview

### ISSUE THREAD

**Issue by smatting** [hakanu/pervane#69]
Bullet points don't seem to render in preveiw.
https://i.imgur.com/s9O87aB.png

 I'm using firefox and pervane 0.0.40

Thankyou for creating pervane. I just started using it and I really like it!

**Comment by smatting** [comment]
Ah, I found the culprit. It's here: https://github.com/hakanu/pervane/blob/master/pervane/static/css/styles.css#L13

**Comment by hakanu** [comment]
This has been annoying me too for some while :)

Thanks for pointing out the culprit. You can send a PR or I will fix it tonight.

**Comment by hakanu** [comment]
Hey Stefan please update to new version via `pip install --upgrade pervane` it's fixed there :)

Thanks for reporting.

**Comment by smatting** [comment]
Just did! Thank you!
